version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    environment:
      DEBUG: recipes:*
      NODE_ENV: development
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
